version: "3.2"

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    expose:
      - "8000"

  redis:
    command: "redis-server"
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"

  server:
    build: ./server
    depends_on:
      - redis
      - dynamodb-local
    image: "codeassignment:server"
    container_name: server
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      REDIS_HOST: redis
      AWS_ENDPOINT: "http://dynamodb-local:8000"

  app:
    build: ./app
    depends_on:
      - server
    image: "codeassignment:app"
    container_name: app
    ports:
      - "3000:3000"
    expose:
      - "3000"
