# Stage I
FROM node:alpine as builder

WORKDIR /app
COPY ["package.json", "yarn.lock", "./"]
RUN yarn install --production
COPY ./ ./
CMD ["yarn", "build"]

# Stage II
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]